# Generated by Django 5.2.6 on 2025-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_product_is_active_swapeduser_avatar_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default='good', max_length=20),
        ),
    ]
